# OS - Ubuntu Based
FROM jbarlow83/ocrmypdf:v17.2.0

# set timezone
ENV TZ=America/Sao_Paulo
RUN set -eux; \
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# setup
RUN apt-get update && apt-get install -y --no-install-recommends \
  curl && \
  # clean
  rm -rf /var/lib/apt/lists/*

# node LTS
RUN curl -sL https://deb.nodesource.com/setup_24.x | bash - && \
  apt-get install -y --no-install-recommends nodejs && \
  # clean
  rm -rf /var/lib/apt/lists/*

# override entrypoint
ENTRYPOINT ["/usr/bin/env"]

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY --chown=node:node package*.json ./

RUN npm install && npm cache clean --force

# Bundle app source
COPY --chown=node:node . .

VOLUME [ "/usr/src/app" ]

EXPOSE 8080

CMD ["npm", "run", "dev"]
